version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      composer-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      composer-major-updates:
        applies-to: "version-updates"
        update-types:
          - "major"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
